blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/algolia/autocomplete/discussions/new
    about: Request a feature to add to Autocomplete.
  - name: Ask a question
    url: https://github.com/algolia/autocomplete/discussions/new
    about: Ask questions and discuss with other community members.
