export type AutocompleteClassNames = {
  form: string;
  input: string;
  inputWrapper: string;
  inputWrapperPrefix: string;
  inputWrapperSuffix: string;
  item: string;
  label: string;
  list: string;
  loadingIndicator: string;
  panel: string;
  panelLayout: string;
  resetButton: string;
  root: string;
  source: string;
  sourceFooter: string;
  sourceHeader: string;
  submitButton: string;
  touchCancelButton: string;
  touchFormContainer: string;
  touchOverlay: string;
  touchSearchButton: string;
  touchSearchButtonIcon: string;
  touchSearchButtonPlaceholder: string;
};
